# -*- coding: utf-8 -*-
"""llm_plugin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CTkh-DsYx9N00ZjMYlv85VIJha7AgkBT
"""

import os
from pathlib import Path

class Config:
    # Paths
    BASE_DIR = Path(__file__).parent
    DATA_DIR = BASE_DIR / "data"
    NCERT_DIR = DATA_DIR / "ncert"
    MCQ_DIR = DATA_DIR / "mcqs"
    KNOWLEDGE_BASE_DIR = DATA_DIR / "knowledge_base"

    # LLM Settings
    DEFAULT_MODEL = "llama3.2:3b"  # Change based on your system
    ALTERNATIVE_MODELS = ["mistral:7b", "phi3:mini", "qwen2:7b"]
    MAX_TOKENS = 2048
    TEMPERATURE = 0.7

    # Memory Settings
    MAX_MEMORY_TURNS = 50
    MEMORY_FILE = DATA_DIR / "session_memory.json"

    # Vector DB Settings
    EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
    CHUNK_SIZE = 500
    CHUNK_OVERLAP = 50

    # UI Settings
    STREAMLIT_PORT = 8501

    @classmethod
    def ensure_directories(cls):
        """Create necessary directories"""
        for dir_path in [cls.DATA_DIR, cls.NCERT_DIR, cls.MCQ_DIR, cls.KNOWLEDGE_BASE_DIR]:
            dir_path.mkdir(parents=True, exist_ok=True)